### ISSUE TITLE
niboSearchSuggestionItem getmLatLng() returns null

### ISSUE THREAD

**Issue by ampersanda** [aliumujib/Nibo#2]
Halo, I am currently using this library but I got a problem which the item.getmLatLng() returns null

```
public NiboPlacesAutoCompleteSearchView.SearchListener getSearchListener() {
        return new NiboPlacesAutoCompleteSearchView.SearchListener() {
            @Override
            public boolean onSuggestion(NiboSearchSuggestionItem niboSearchSuggestionItem) {

                Log.e(TAG, String.valueOf(niboSearchSuggestionItem.getmLatLng())); // this log is null
                return false;
            }

            ...
        }
    }
```

I fixed it by using `geoDataClient.getPlaceById(niboSearchSuggestionItem.getPlaceID())` to get `Place` with id

**Comment by aliumujib** [comment]
Hello ampersanda,
Could you post the full stacktrace instead, it would make it much easier to fix the issue.

Regards,
Mujib.

**Comment by ampersanda** [comment]
I just log it and it jut returns null

**Comment by aliumujib** [comment]
Issue will be fixed in the next version. Sorry about the late reply. I was away.

Regards, 
Mujib.
