### ISSUE TITLE
Add autocomplete filter

### ISSUE THREAD

**Issue by ampersanda** [aliumujib/Nibo#3]
Hello, I am really glad using your library, but I have  a case which is only showing name of places on a country. 

I used to `AutocompleteFilter` with Google Places API, and maybe if this library could do that, how to use it?

```
AutocompleteFilter autocompleteFilter = new AutocompleteFilter.Builder()
                .setCountry(Constants.INDONESIA)
                .build();
```
I saw in your `SuggestionsRepository` class, and `null` is passing  in the filter

**Comment by aliumujib** [comment]
Thank you for your suggestion. I will add this functionality in the next version.
