### ISSUE TITLE
Accessing the location.

### ISSUE THREAD

**Issue by jayanthsaikiran** [aliumujib/Nibo#9]
Hey how can we access the location which is clicked on the search bar? Does have any variable for accessing it or any method which returns location or LatLng?

**Comment by aliumujib** [comment]
I will update the readme today. Sorry, should have done it a while back.

**Comment by jayanthsaikiran** [comment]
Thanks for the reply please tell how can i access it!

**Comment by aliumujib** [comment]
@Teja-developer @jayanthsaikiran what functionality of the app are you using exactly... the above code snippet is for when you are using the autocomplete searchbar ONLY, if you want to use the place picker... you have to override onActivityResult in your fragment and then check for the result ... the following is an example, also please look through the example project.

```
@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if (resultCode == Activity.RESULT_OK && requestCode == 300) {
            NiboSelectedPlace selectedPlace = data.getParcelableExtra(NiboConstants.SELECTED_PLACE_RESULT);
            Toast.makeText(this, selectedPlace.getPlaceAddress(), Toast.LENGTH_LONG).show();
        } else if (resultCode == Activity.RESULT_OK && requestCode == 200) {
            NiboSelectedOriginDestination selectedOriginDestination = data.getParcelableExtra(NiboConstants.SELECTED_ORIGIN_DESTINATION_RESULT);
            Toast.makeText(this, selectedOriginDestination.getOriginFullName() + " - " + selectedOriginDestination.getDestinationFullName(), Toast.LENGTH_LONG).show();
        } else {
            Toast.makeText(this, "Error getting results", Toast.LENGTH_LONG).show();
        }

    }
```

**Comment by aliumujib** [comment]
No further activity
